trigger:
  - main

pool:
  vmImage: ubuntu-latest

stages:
  - stage: validate
    displayName: Run tests and pre-commit
    jobs:
      - job: pre_commit
        displayName: Run pre-commit
        steps:
          - task: UsePythonVersion@0
            displayName: Use Python $(python-version)
            inputs:
              versionSpec: "$(python-version)"

          - script: |
              python -m pip install --upgrade pip
              pip install pre-commit
            displayName: Install pre-commit

          - script: |
              pre-commit run --all-files
            displayName: Run pre-commit

      - job: pytest
        dependsOn: pre_commit
        displayName: Run tests

        steps:
          - task: UsePythonVersion@0
            displayName: Use Python $(python-version)
            inputs:
              versionSpec: "$(python-version)"

          - script: |
              python -m pip install --upgrade pip
              pip install pytest pytest-azurepipelines
            displayName: "Install test dependencies"

          - script: |
              pytest
            displayName: "Run pytest"
  - stage: publish
    displayName: Upload to PyPI
    dependsOn: validate
    jobs:
      - job: upload
        displayName: Upload
        steps:
          - task: UsePythonVersion@0
            displayName: Use Python $(python-version)
            inputs:
              versionSpec: "$(python-version)"
          - script: |
              python -m pip install --upgrade pip
              python -m pip install --upgrade build setuptools twine
            displayName: Install Build Dependencies
          - script: |
              python -m build
            displayName: Build sdist And wheel
          - script: |
              python -m twine upload --skip-existing --verbose -p $(pypi-api-token) -u __token__ --repository $(pypi-project-name) --repository-url https://test.pypi.org/legacy/ dist/*
            displayName: Upload to PyPi (Twine)
